# Docs - https://alacritty.org/config-alacritty.html
# YAML example - https://gist.github.com/sts10/df620672662fe4c6f03ac296a02b8e72 

live_config_reload = true

[env]
term = "xterm-256color"

[scrolling]
history = 100000

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.93

[window.padding]
x = 16
y = 16

[window.dimensions]
columns = 160
lines = 48

[window.position]
x = 32
y = 96

[colors]
# transparent_background_colors = true
primary = { foreground = "#41FF00" }
cursor = { text = "#000000", cursor = "#ffffff" }

# inspiration: https://github.com/joshmedeski/dotfiles/blob/main/.config/alacritty/alacritty.toml
[keyboard]
bindings = [
    { key = "Key1", mods = "Command", chars = "\u00021" },
    { key = "Key2", mods = "Command", chars = "\u00022" },
    { key = "Key3", mods = "Command", chars = "\u00023" },
    { key = "Key4", mods = "Command", chars = "\u00024" },
    { key = "Key5", mods = "Command", chars = "\u00025" },
    { key = "Key6", mods = "Command", chars = "\u00026" },
    { key = "Key7", mods = "Command", chars = "\u00027" },
    { key = "Key8", mods = "Command", chars = "\u00028" },
    { key = "Key9", mods = "Command", chars = "\u00029" },
    { key = "E", mods = "Command", chars = "\u0002e" },
]

[font]
size = 14.0
normal = { family = "FiraCode Nerd Font Mono", style = "Medium" }
# normal = { family = "Hack Nerd Font" }

# brew search font- | grep fira
# brew install --cask font-fira-code-nerd-font

# [font.normal]
# family = "FiraCode Nerd Font"
# style = "Medium"

# [font.bold]
# family = "FiraCode Nerd Font"
# style = "Heavy"

# [font.bold_italic]
# family = "FiraCode Nerd Font"
# style = "Heavy Italic"

# [font.italic]
# family = "FiraCode Nerd Font"
# style = "Medium Italic"
