# Docs - https://alacritty.org/config-alacritty.html
# YAML example - https://gist.github.com/sts10/df620672662fe4c6f03ac296a02b8e72 

live_config_reload = true

[env]
term = "xterm-256color"

[scrolling]
history = 100000

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 16
y = 16

[window.dimensions]
columns = 160
lines = 48

[window.position]
x = 32
y = 96

[colors]
# transparent_background_colors = true
primary = { foreground = "#41FF00"}
cursor = { text = "#000000", cursor = "#ffffff" }


[font]
size = 14.0
normal = { family = "Hack Nerd Font"}

# [font.bold]
# family = "FiraCode Nerd Font"
# style = "Heavy"

# [font.bold_italic]
# family = "FiraCode Nerd Font"
# style = "Heavy Italic"

# [font.italic]
# family = "FiraCode Nerd Font"
# style = "Medium Italic"

# [font.normal]
# family = "FiraCode Nerd Font"
# style = "Medium"